<?php

/**
 * @file
 * Implementation of hook_form_alter.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\node\Entity\NodeType;
use Drupal\taxonomy\Entity\Term;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\field\Entity\FieldStorageConfig;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\field\Entity\FieldConfig;
use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CloseModalDialogCommand;

/**
 * @file
 * Implements hook_form_alter.
 */

/**
 * Add a machine name field to the heritage text.
 *
 * Opens and closes form in modal dialog.
 */
function heritage_schema_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // print_r($form_id);
  // echo "</br>";.
  // $str = "1.1";
  // $arg = explode('.',$str);
  // $chapter_name = 'Chapter '.$arg[0];
  // print_r($chapter_name);exit;
  // $languages = \Drupal::service('language_manager')->getLanguages(LanguageInterface::STATE_CONFIGURABLE);
  //  $arg2 = "Malayalam";
  //  foreach ($languages as $language) {
  //              if($arg2 == $language->getName()) {
  //                $arg2 = $language->getId();
  // }
  //            }
  // print_r($arg2);exit;
  // Find the route name of the form
  // $route_name = \Drupal::routeMatch()->getRouteName();
  // print_r($route_name);
  if ($form_id == 'node_heritage_text_form') {
    $form['field_machine_name']['#access'] = FALSE;
    $form['field_levels']['#access'] = FALSE;
    $form['field_level_labels']['#access'] = FALSE;
    // $form['#validate'][] = '_heritage_text_form_validate';
  }
  if ($form_id == 'node_heritage_text_edit_form') {
    $form['field_machine_name']['#access'] = FALSE;
    $form['field_levels']['#access'] = FALSE;
    $form['field_level_labels']['#access'] = FALSE;
  }
  if ($form_id == 'node_source_node_form') {
    $form['actions']['submit']['#submit'][] = 'redirect_to_text_node';

  }

  if ($form_id == 'node_heritage_text_form' || $form_id == 'node_heritage_text_edit_form' || $form_id == 'node_source_node_form' || $form_id == 'node_source_node_edit_form') {
    $form['#attached']['library'][] = 'core/drupal.dialog.ajax';
    // Echo $_GET['textid'];
    // print_r($_GET['textid']);.
    $options = [
      'attributes' => [
        'class' => ['use-ajax', 'button'],
        'data-dialog-type' => 'modal',
        'data-dialog-options' => json_encode(['width' => 400]),
      ],
      // 'query' => ['destination' => \Drupal::url('<current>')],
    ];
    $form['field_author_name']['add_term_link'] = [
      '#title' => t('Add author'),
      '#type' => 'link',
      '#url' => Url::fromRoute('entity.taxonomy_term.add_form', ['taxonomy_vocabulary' => 'authors'], $options),

    ];

    $form['field_publisher_name']['add_term_link'] = [
      '#title' => t('Add publisher'),
      '#type' => 'link',
      '#url' => Url::fromRoute('entity.taxonomy_term.add_form', ['taxonomy_vocabulary' => 'publishers'], $options),

    ];

    // $form['actions']['submit']['#submit'][] = '_modal_form_example_ajax_submit';
    // $form['actions']['submit']['#attributes']['class'][] = 'use-ajax-submit';
  }

  /* The second function adds an extra submit function (which will be executed after Drupal finishes processing the node) and the first function adds the command to close the Dialog when the node has been created. */

  if ($form_id == 'taxonomy_term_authors_form' || $form_id == 'taxonomy_term_publishers_form') {
    $form['actions']['submit']['#submit'][] = '_modal_form_example_ajax_submit';
    $form['actions']['submit']['#attributes']['class'][] = 'use-ajax-submit';

  }

  if ($form_id == 'node_gita_form') {
    // Check for duplicates.
    $form['#validate'][] = 'check_node_exists';
    // $form['actions']['submit']['#submit'][] = 'content_form_submit';
  }

}

/**
 * @file
 * Implements hook functions.
 */

/**
 * Presaves the text id in the field_heritage_text_id.
 */
function heritage_schema_node_presave(EntityInterface $entity) {

  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'source_node') {
    $text_node = $_GET["textid"];
    // print_r($text_node);exit;
    // Hook_entity_presave gets called before the entity is saved
    // And also before you save the edits.
    if (isset($text_node)) {
      $entity->field_heritage_text_id->target_id = $text_node;

    }

  }

}

/**
 * Create content type and vocabulary and add basic fields.
 */
function heritage_schema_node_insert(NodeInterface $node) {

  if ($node->getType() == 'heritage_text') {
    $response = new RedirectResponse(\Drupal::url('heritage_schema.addtoc', ['node' => $node->id()], ['absolute' => TRUE]));
    $response->send();
  }
  if ($node->getType() == "source_node") {

    $params = [
      'source_nodeId' => $node->id(),
      'title' => $node->title->value,
      'language' => $node->field_language->target_id,
      'author' => $node->field_author_name->target_id,
      'format' => [$node->field_format->value],
      'type' => $node->field_type->value,
      'parent_id' => $node->field_parent_source->target_id,
    ];
    $text_node = $_GET["textid"];
    if (isset($text_node)) {

      _add_source_info($params, $_GET["textid"]);
    }

  }

}

/**
 * Updates source info.
 */
function heritage_schema_entity_update(EntityInterface $entity) {

  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'source_node') {

    $params = [
    // 'source_nodeId' => $node->id(),
      'title' => $entity->title->value,
      'language' => $entity->field_language->target_id,
      'author' => $entity->field_author_name->target_id,
      'format' => [$entity->field_format->value],
      'type' => $entity->field_type->value,
      'parent_id' => $entity->field_parent_source->target_id,

    ];

    $machine_names = []; $types = [];$cardinality = [];
    $format = '';
    $format_tmp_array = $params['format'];
    for ($i = 0; $i < count($format_tmp_array); $i++) {
      if ($i == 0) {
        $format = $format_tmp_array[$i];
      }
      else {
        $format = $format . ',' . $format_tmp_array[$i];
      }
    }
    $old_source_info = db_query("SELECT * FROM `heritage_source_info` WHERE id = :sourceid", [':sourceid' => $entity->id()])->fetchAll();
    $textid = $old_source_info[0]->text_id;
    $node = Node::load($textid);

    // Update source node structure in database.
    db_update('heritage_source_info')
      ->fields([
        'title' => $params['title'],
        'language' => $params['language'],
        'author' => $params['author'],
        'format' => $format,
        'type' => $params['type'],
        'parent_id' => $params['parent_id'],

      ])
      ->condition('id', $entity
        ->id())
      ->execute();

    $textname = $node->field_machine_name->value;
    $field_name = 'field_' . $textname . '_' . $entity->id();
    for ($i = 0; $i < count($format_tmp_array); $i++) {
      $machine_names[] = $field_name . '_' . strtolower($format_tmp_array[$i]);
      if ($format_tmp_array[$i] == 'text') {
        $types[] = 'text_long';
        $labels[] = $params['title'];
        $cardinality[] = 1;
      }
      if ($format_tmp_array[$i] == 'audio') {
        $types[] = 'file';
        $labels[] = $format_tmp_array[$i] . ' of ' . $params['title'];
        $cardinality[] = -1;
      }
      if ($format_tmp_array[$i] == 'video') {
        $types[] = 'file';
        $labels[] = $format_tmp_array[$i] . ' of ' . $params['title'];
        $cardinality[] = -1;
      }
    }

  }
}

/**
 * Delete test source.
 */
function heritage_schema_entity_delete(EntityInterface $entity) {

  // $format = db_query("SELECT format FROM `heritage_source_info` WHERE id = :sourceid AND text_id = :textid", [':sourceid' => $entity->id(),':textid' => 'gita'])->fetchField();
  // $field_name = 'field_gita'. '_' . $entity->id() .'_'. $format;
  // FieldStorageConfig::loadByName('node','gita',$field_name)->delete();
  // FieldConfig::loadByName('node',$field_name)->delete();
  db_delete('heritage_source_info')
    ->condition('id', $entity->id())
    ->execute();

}

/**
 * Custom function to add a field to an entity.
 *
 * @param string $bundle
 *   Name of the entity bundle.
 * @param object $entity_type
 *   Type of entity ie. whether node/taxonomy/user.
 * @param array $labels
 *   Array of field labels.
 * @param string $machine_names
 *   Array of Machine Names of the field.
 * @param array $field_types
 *   Array of Field Types to be added.
 */
function add_other_fields($bundle, $entity_type, array $labels, $machine_names, array $field_types, array $format_tmp_array, array $cardinality) {
  for ($i = 0; $i < count($field_types); $i++) {
    $fieldname = strtolower($machine_names[$i]);
    if ($field_types[$i] == 'entity_reference') {
      $handler = 'default:taxonomy_term';
      $handler_settings = ['target_bundles' => [$bundle]];
      $settings_create = ['target_type' => 'taxonomy_term'];
      $settings_config = ['handler' => $handler, 'handler_settings' => $handler_settings];
    }
    elseif ($field_types[$i] == 'file' && $format_tmp_array[$i] == 'audio') {
      $handler = 'default';
      $handler_settings = [];
      $settings_create = [];
      $settings_config = [
        'handler' => $handler,
        'handler_settings' => $handler_settings,
        'file_extensions' => 'mp3',
        'file_directory' => $bundle,
      ];
    }
    elseif ($field_types[$i] == 'file' && $format_tmp_array[$i] == 'video') {
      $handler = 'default';
      $handler_settings = [];
      $settings_create = [];
      $settings_config = [
        'handler' => $handler,
        'handler_settings' => $handler_settings,
        'file_extensions' => 'mp4',
        'file_directory' => $bundle,
      ];
    }

    else {
      $handler = 'default';
      $handler_settings = [];
      $settings_create = [];
      $settings_config = [
        'handler' => $handler,
        'handler_settings' => $handler_settings,
      ];
    }
    if (empty($fieldStorageMicrositesfield = FieldStorageConfig::loadByName($entity_type, $fieldname))) {
      $fieldStorage = FieldStorageConfig::create(
      [
        'field_name'             => $fieldname,
        'entity_type'            => $entity_type,
        'type'                   => $field_types[$i],
        'translatable'           => TRUE,
        'persist_with_no_fields' => FALSE,
        'cardinality'             => $cardinality[$i],
        'settings'                 => $settings_create,
      ]
      );
      $fieldStorageSaved = $fieldStorage->save();
    }
    $all_bundle_fields = \Drupal::service('entity_field.manager')->getFieldDefinitions($entity_type, $bundle);
    if (!isset($all_bundle_fields[$fieldname])) {
      $field = FieldConfig::create(
                        [
                          'entity_type' => $entity_type,
                          'field_name' => $fieldname,
                          'bundle' => $bundle,
                          'label' => $labels[$i],
                          'settings' => $settings_config,
                        ]
      );
      $field->save();
      // Manage form display settings for entity_reference field types
      // options_shs stands for the machine name of the simple hierarchy select module enabled.
      if ($field_types[$i] == 'entity_reference') {
        entity_get_form_display($entity_type, $bundle, 'default')
          ->setComponent($fieldname, [
            'type' => 'options_shs',
          ])
          ->save();

      }
      else {

        // Make the field available in the entity creation form.
        entity_get_form_display($entity_type, $bundle, 'default')
          ->setComponent(
        $fieldname
        )
          ->save();
      }

      // Assign display settings for the 'default' and 'teaser' view modes.
      entity_get_display($entity_type, $bundle, 'default')
        ->setComponent($fieldname)
        ->save();
    }
    else {
      $field_info = FieldConfig::loadByName($entity_type, $bundle, $fieldname);
      $field_info->setLabel($labels[$i]);
      $field_info->save();
    }
  }
  $message = t("Fields added successfully");
  return $message;
}

/**
 * Custom function to add a vocabulary for the heritage text.
 *
 * @param string $title
 *   Title of the content type.
 * @param string $machineName
 *   Unique machine name of the content type.
 */
function add_vocabulary($title, $machineName) {
  $vocabularies = Vocabulary::loadMultiple();
  if (!isset($vocabularies[$machineName])) {
    $vocabulary = Vocabulary::create(
    [
      'vid' => $machineName,

      'description' => t('Vocabulary for storing the levels of heritage text <em> @title </em>.', ['@title' => $title]),
      'name' => $title,
    ]
    );
    $vocabulary->save();
    $labels = ['Index', 'Title', 'No.of Sub Levels', 'Position'];
    $machine_names = [
      'field_index',
      'field_title',
      'field_sub_levels',
      'field_position',
    ];
    $types = ['integer', 'text', 'integer', 'text'];
    $cardinality = [1, 1, 1, 1];
    $format_tmp_array = [];
    $field_status = add_other_fields($vocabulary->id(), 'taxonomy_term', $labels, $machine_names, $types, $format_tmp_array, $cardinality);
  }
  $message = t(
        "Vocabulary @a added successfully",
        ['@a' => $title]
  );
  return $message;
}

/**
 * Custom function to add a term to a vocabulary.
 *
 * @param int $id
 *   Index of the term - Relative position in the heritage text structure.
 * @param string $term_name
 *   Name of the taxonomy term that has to be created.
 * @param string $vid
 *   Vocabulary name of the term.
 * @param int $parent
 *   Parent id of the term, if any.
 */
function add_term($id, $term_name, $vid, $parent = NULL) {
  $term = Term::create([
    'vid' => $vid,
    'name' => $term_name,
    'parent' => [$parent],
  ]);
  $term->set('field_index', $id);
  if ($parent != NULL) {
    $parent_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($parent);
    $parent_position = $parent_term->field_position->value;
    $sublevels = $parent_term->field_sub_levels->value;
    if (!isset($sublevels)) {
      $sublevels = 1;
    }
    else {
      $sublevels = $sublevels + 1;
    }
    $parent_term->field_sub_levels->value = $sublevels;
    $parent_term->save();
    $term_position = $parent_position . '.' . $id;
  }
  else {
    $term_position = $id;
  }
  $term->set('field_position', $term_position);
  $term->save();
  $message = t(
        "Taxonomy term @a added successfully",
        ['@a' => $term_name]
  );
  return $message;
}

/**
 * Custom function to delete a term to a vocabulary.
 *
 * @param int $id
 *   Index of the term - Relative position in the heritage text structure.
 * @param string $term_name
 *   Name of the taxonomy term that has to be deleted.
 * @param string $vid
 *   Vocabulary name of the term.
 * @param int $parent
 *   Parent id of the term, if any.
 */
function delete_term($id, $term_name, $vid, $parent = NULL) {
  if ($parent == NULL) {
    $parent = 0;
  }
  // Get the taxonomy term id, load the term and delete it.
  $tid_to_delete = db_query("SELECT tid FROM `taxonomy_term_field_data` WHERE name = :name AND vid = :vid AND tid IN (SELECT entity_id FROM `taxonomy_term__parent` WHERE parent_target_id = :parent)", [
    ':name' => $term_name,
    ':vid' => $vid,
    ':parent' => $parent,
  ])->fetchField();
  $controller = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $term_to_delete = $controller->load($tid_to_delete);
  $controller->delete($term_to_delete);

  if ($parent != 0) {
    $parent_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($parent);
    $sublevels = $parent_term->field_sub_levels->value;
    if (!isset($sublevels)) {
      $sublevels = 0;
    }
    else {
      $sublevels = $sublevels - 1;
    }
    $parent_term->field_sub_levels->value = $sublevels;
    $parent_term->save();
  }
  $message = t(
        "Taxonomy term @a deleted successfully",
        ['@a' => $term_name]
  );
  return $message;
}

/**
 * Custom function to create a content type.
 *
 * @param string $title
 *   Title of the content type.
 * @param string $machineName
 *   Unique machine name of the content type.
 */
function create_content_type($title, $machineName) {
  $content_type = NodeType::create([
    'type' => $machineName,
    'name' => $title,

    'description' => t('Content type for <em>@title</em> with trasnliteration enabled',
  ['@title' => $title]),
    'new_revision' => FALSE,
    'status' => TRUE,
    'preview_mode' => 0,
    'display_submitted' => FALSE,
  ]);
  $content_type->save();
  ($content_type);
  return $content_type;
}

/**
 * Batch operation for creating taxonomy terms.
 */
function create_taxonomy_terms_batch($id, $vid, $term_name, $parent = NULL, $operation_details, &$context) {
  // Create taxonomy term.
  $term_status = add_term($id, $term_name, $vid, $parent);

  // Store some results for post-processing in the 'finished' callback.
  $context['results'][] = $id;

  // Optional message displayed under the progressbar.
  $context['message'] = t('Running Batch "@id" @details',
        ['@id' => $id, '@details' => $operation_details]
  );
}

/**
 * Batch 'finished' callback used by create_taxonomy_terms_batch.
 */
function create_taxonomy_terms_batch_finished($success, $results, $operations) {
  $messenger = \Drupal::messenger();
  if ($success) {
    // Here we could do something meaningful with the results.
    // We just display the number of nodes we processed...
    $messenger->addMessage(t('@count terms created.', ['@count' => count($results)]));
  }
  else {
    // An error occurred.
    // $operations contains the operations that remained unprocessed.
    $error_operation = reset($operations);
    $messenger->addMessage(
    t('An error occurred while processing @operation with arguments : @args',
                [
                  '@operation' => $error_operation[0],
                  '@args' => print_r($error_operation[0], TRUE),
                ]
    )
    );
  }
}

/**
 * Batch operation for deleting taxonomy terms.
 */
function delete_taxonomy_terms_batch($id, $vid, $term_name, $operation_details, &$context, $parent = NULL) {
  // Delete taxonomy term.
  $term_status = delete_term($id, $term_name, $vid, $parent);

  // Store some results for post-processing in the 'finished' callback.
  $context['results'][] = $id;

  // Optional message displayed under the progressbar.
  $context['message'] = t('Running Batch "@id" @details',
        ['@id' => $id, '@details' => $operation_details]
  );
}

/**
 * Batch 'finished' callback used by delete_taxonomy_terms_batch.
 */
function delete_taxonomy_terms_batch_finished($success, $results, $operations) {
  $messenger = \Drupal::messenger();
  if ($success) {
    // Here we could do something meaningful with the results.
    // We just display the number of nodes we processed...
    $messenger->addMessage(t('@count terms deleted.', ['@count' => count($results)]));
  }
  else {
    // An error occurred.
    // $operations contains the operations that remained unprocessed.
    $error_operation = reset($operations);
    $messenger->addMessage(
    t('An error occurred while processing @operation with arguments : @args',
                [
                  '@operation' => $error_operation[0],
                  '@args' => print_r($error_operation[0], TRUE),
                ]
    )
    );
  }
}

/**
 * Custom function to add source to a text.
 *
 * @param array $params
 *   An array containing title, language, format, author and type of the source.
 * @param int $textid
 *   Unique Id of the heritage text.
 *
 * @return bool
 *   Returns a boolean
 */
function _add_source_info(array $params, $textid) {
  $machine_names = []; $types = [];$cardinality = [];
  $format = '';
  $format_tmp_array = $params['format'];
  for ($i = 0; $i < count($format_tmp_array); $i++) {
    if ($i == 0) {
      $format = $format_tmp_array[$i];
    }
    else {
      $format = $format . ',' . $format_tmp_array[$i];
    }
  }
  $node = Node::load($textid);
  // Insert source node structure to database.
  $db = \Drupal::database();
  $source_id = $db->insert('heritage_source_info')
    ->fields([
      'id' => $params['source_nodeId'],
      'text_id' => $textid,
      'title' => $params['title'],
      'language' => $params['language'],
      'author' => $params['author'],
      'format' => $format,
      'type' => $params['type'],
      'parent_id' => $params['parent_id'],
                                // Added the source node id.
    ])
    ->execute();
  $textname = $node->field_machine_name->value;
  $field_name = 'field_' . $textname . '_' . $source_id;
  for ($i = 0; $i < count($format_tmp_array); $i++) {
    $machine_names[] = $field_name . '_' . strtolower($format_tmp_array[$i]);
    if ($format_tmp_array[$i] == 'text') {
      $types[] = 'text_long';
      $labels[] = $params['title'];
      $cardinality[] = 1;
    }
    if ($format_tmp_array[$i] == 'audio') {
      $types[] = 'file';
      $labels[] = $format_tmp_array[$i] . ' of ' . $params['title'];
      $cardinality[] = -1;
    }
    if ($format_tmp_array[$i] == 'video') {
      $types[] = 'file';
      $labels[] = $format_tmp_array[$i] . ' of ' . $params['title'];
      $cardinality[] = -1;
    }
  }

  // print_r($textname);print_r($field_name);print_r($machine_names);exit;
  // pass the $format_tmp_array in the function.
  $field_status = add_other_fields($textname, 'node', $labels, $machine_names, $types, $format_tmp_array, $cardinality);
  return TRUE;
}

/**
 * Custom function to update source of a text.
 *
 * @param array $params
 *   An array containing title, language, format, author and type of the source.
 * @param int $sourceid
 *   Unique Id of the source of the heritage text.
 *
 * @return bool
 *   Return a boolean
 */
function _update_source_info(array $params, $sourceid) {
  $machine_names = []; $types = [];$cardinality = [];
  $format = '';
  $format_tmp_array = $params['format'];
  for ($i = 0; $i < count($format_tmp_array); $i++) {
    if ($i == 0) {
      $format = $format_tmp_array[$i];
    }
    else {
      $format = $format . ',' . $format_tmp_array[$i];
    }
  }
  $old_source_info = db_query("SELECT * FROM `heritage_source_info` WHERE id = :sourceid", [':sourceid' => $sourceid])->fetchAll();
  $textid = $old_source_info[0]->text_id;
  $node = Node::load($textid);
  // Update source node structure in database.
  $db = \Drupal::database();
  $db->update('heritage_source_info')
    ->fields([
      'title' => $params['title'],
      'language' => $params['language'],
      'author' => $params['author'],
      'format' => $format,
      'type' => $params['type'],
      'parent_id' => $params['parent_id'],
    ])
    ->condition('id', $sourceid, '=')
    ->execute();
  $textname = $node->field_machine_name->value;
  $field_name = 'field_' . $textname . '_' . $sourceid;
  for ($i = 0; $i < count($format_tmp_array); $i++) {
    $machine_names[] = $field_name . '_' . strtolower($format_tmp_array[$i]);
    if ($format_tmp_array[$i] == 'text') {
      $types[] = 'text_long';
      $labels[] = $params['title'];
      $cardinality[] = 1;
    }
    if ($format_tmp_array[$i] == 'audio') {
      $types[] = 'file';
      $labels[] = $format_tmp_array[$i] . ' of ' . $params['title'];
      $cardinality[] = -1;
    }
    if ($format_tmp_array[$i] == 'video') {
      $types[] = 'file';
      $labels[] = $format_tmp_array[$i] . ' of ' . $params['title'];
      $cardinality[] = -1;
    }
  }
  // print_r($textname);print_r($field_name);print_r($machine_names);exit;
  $field_status = add_other_fields($textname, 'node', $labels, $machine_names, $types, $format_tmp_array, $cardinality);
  return TRUE;
}

/**
 * Function to find the depth of the given element.
 */
function find_depth($input, $startDepth = 0) {
  if (is_array($input)) {
    $max = $startDepth;
    foreach ($input as $i) {
      // Check what the depth of the given element is.
      $result = find_depth($i, $startDepth + 1);
      // We only care about the maximum value.
      if ($result > $max) {
        $max = $result;
      }
    }
    return $max;
  }
  else {
    // This isn't an array, so it's assumed not to be a container.
    // This doesn't add any depth to the parent array,
    // So just return $startDepth.
    return $startDepth;
  }
}

/**
 * @param string $vid
 *   Vocabulary name of the term.
 * @param string $term
 *   Name of the taxonomy term that needs to be checked.
 */
function check_taxonomy($vid, $term_name) {

  // If ($terms = taxonomy_term_load_multiple_by_name($term_name, $vid)) {
  //   $term_name = reset($terms);
  // }
  // else {
  //   $term_name = Term::create([
  //     'name' => $term_name,
  //     'vid' => $vid,
  //   ]);
  //   $term_name->save();
  // }
  $properties = [];
  if (!empty($term_name)) {
    $properties['name'] = $term_name;
  }
  if (!empty($vid)) {
    $properties['vid'] = $vid;
  }
  $terms = \Drupal::entityManager()->getStorage('taxonomy_term')->loadByProperties($properties);
  // If the term is already present.
  if ($terms) {
    // Avoid creating multiple terms by same name.
    $term_name = reset($terms);

  }
  else {
    $term_name = Term::create([
      'name' => $term_name,
      'vid' => $vid,
    ]);
    $term_name->save();
  }

  return $term_name->id();

}

/**
 * @param string $title
 *   Title of the content type.
 * @param string $format
 *   Format of the content.
 * @param string $type
 *   Type of content.
 * @param int $language
 *   ID of the language.
 * @param int $author
 *   ID of the author.
 * @param int $textid
 *   ID of the heritage text.
 */
function create_sourceNode($title, $format, $type, $language, $author, $textid) {

  $node = entity_create('node',
                [
                  'type' => 'source_node',
                  'title' => $title,

                  'field_format' => $format,
                  'field_type' => $type,
                  'field_language' => [
                    'target_id' => $language,
                  ],
                  'field_author_name' => [
                    'target_id' => $author,
                  ],

                  'field_heritage_text_id' => $textid,

                ]

                );
  $node->save();

  return $node->id();

}

/**
 *
 */
function add_source_content($textid, $positional_index, $language, $field_name, $field_content) {

  $node = Node::load($textid);
  // $node_storage = $this->entityTypeManager->getStorage('node');
  // $node = $node_storage->load($sourceid);
  $language_id = db_query('SELECT tid FROM `taxonomy_term_field_data` WHERE name = :language', [':language' => $language])->fetchField();

  $language = $language_id;

  $node->set('field_positional_index', $positional_index);
  $node->set('field_language', $language);
  $node->set($field_name, $field_content);

  $node->save();

}

/**
 * Custom function to redirect source of a text.
 */
function redirect_to_text_node(array $form, FormStateInterface $form_state) {

  $nid = $_GET["textid"];

  $form_state->setRedirect('entity.node.canonical', ['node' => $nid]);
}

/**
 * Close the Modal and redirect the user to the current page.
 *
 * @param array $form
 *   The form that will be altered.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   FormState Object.
 */
function _modal_form_example_ajax_submit(array $form, FormStateInterface &$form_state) {
  $response = new AjaxResponse();
  $response->addCommand(new CloseModalDialogCommand());
  $form_state->setResponse($response);

}

/**
 * Custom function to check for node duplicated.
 */
function check_node_exists($form, FormStateInterface &$form_state) {

  $title = $form_state->getValue('title')[0]['value'];

  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();

  // print_r($language);exit;
  $node_title = db_query('SELECT title FROM `node_field_data` WHERE title = :title AND langcode = :langcode', [':title' => $title, ':langcode' => $language])->fetchField();

  if (!empty($node_title)) {
    // Then the title already exists.
    $form_state->setErrorByName('title', t('Node of the given title and language already exists.'));

  }

}

/**
 *
 */
// Function content_form_submit($form, FormStateInterface $form_state) {
//   $nodeid = $form_state->getValue('nid');
//   $node = Node::load($nodeid);
//   if (is_object($node)) {
//     $node->status->value = 0;
//     $node->save();
//   }
// }

/**
 * Custom function to calculate the sublevels for a text.
 */
function calculate_sublevels($textname, $chapter_tid) {

  // $chapter_tid = db_query("SELECT tid FROM `taxonomy_term_field_data` WHERE name = :chapter AND vid = :textname", [':chapter' => $chapter, 'textname' => $textname])->fetchField();
  $sublevels = db_query("SELECT field_sub_levels_value FROM `taxonomy_term__field_sub_levels` WHERE entity_id = :chapterid AND bundle = :textname", [':chapterid' => $chapter_tid, ':textname' => $textname])->fetchField();

  return $sublevels;

}

/**
 *
 */
function collect_metadata($entityid, $field_name, $langcode) {
  $metadata = db_query('SELECT metadata FROM `heritage_field_meta_data` WHERE nid = :entityid AND language = :langcode AND field_name = :field_name', [':entityid' => $entityid, ':langcode' => $langcode, ':field_name' => $field_name])->fetchField();

  return $metadata;
}

/**
 *
 */
function get_entityId($positional_index, $bundle, $langcode) {
  $term_position = db_query('SELECT entity_id FROM `taxonomy_term__field_position` WHERE field_position_value = :position AND bundle = :bundle', [':position' => $positional_index, ':bundle' => $bundle])->fetchField();

  $entityid = db_query('SELECT entity_id FROM `node__field_positional_index` WHERE field_positional_index_target_id = :term_position AND langcode = :langcode', [':term_position' => $term_position, ':langcode' => $langcode])->fetchField();

  return (int) $entityid;

}

/**
 *
 */
function doesBundleHaveField($entity_type, $bundle, $field_name) {
  $all_bundle_fields = \Drupal::service('entity_field.manager')->getFieldDefinitions($entity_type, $bundle);
  return isset($all_bundle_fields[$field_name]);
}

/**
 * Returns message and statuscose as array
 */
// function display_contents($textname, $position = NULL, $parameters, $langcode, $metadata = NULL, $mool_shloka = NULL) {
//   $contents = [];
//   $response = [];

//   // Find the nodes of type == 'ramayanam_test' and langcode = 'dv'.
//   if ($position = NULL) {
//     $available_texts = db_query("SELECT * FROM `node_field_data` WHERE type = :textname AND langcode = :langcode", [':textname' => $textname, ':langcode' => $langcode])->fetchAll();

//     if (count($available_texts) > 0) {
//       for ($i = 0; $i < count($available_texts); $i++) {
//         $text_info = [];
//         $mool_shloka = [];

//         // Flag to test if the field exists.
//         $flag = TRUE;
//         $mool_shloka_flag = TRUE;
//         $other_fields = [];

//         foreach ($parameters as $key => $parameter) {
//           $parameter_info = explode('_', $key);
//           if ($parameter_info[0] == 'field') {
//             if (count($parameter_info) >= 3) {
//               $mool_shloka_flag = FALSE;
//               $field = 'field_' . $parameter_info[1] . '_' . $parameter_info[2] . '_' . $parameter_info[3];

//               $field_name = 'field_' . $parameter_info[1] . '_' . $parameter_info[2] . '_' . $parameter_info[3] . '_value';

//               $table_name = 'node__field_' . $textname . '_' . $parameter_info[2] . '_' . $parameter_info[3];


//               if (doesBundleHaveField('node', $textname, $field) == TRUE) {
//                 $table_lang = db_query("SELECT langcode FROM " . $table_name . " WHERE bundle = :textname", [':textname' => $textname])->fetchField();

//                 if ($table_lang == 'en') {
//                   // TODO: CHECK the get_entityid function for ramayanam.
//                   $entityid_en = get_entityId($position, $textname, 'en');
//                   $field_content = db_query("SELECT $field_name FROM " . $table_name . " WHERE bundle = :textname AND entity_id = :entityid AND langcode = :langcode", [':textname' => $textname, ':entityid' => $entityid_en, ':langcode' => 'en'])->fetchField();

//                   $other_fields['content'] = $field_content;
//                   $text_info['nid'] = json_decode($available_texts[$i]->nid, TRUE);
//                   $text_info['title'] = $available_texts[$i]->title;

//                 }
//                 else {
//                   $entityid_dv = get_entityId($position, $textname, $langcode);
//                   $field_content = db_query("SELECT $field_name FROM " . $table_name . " WHERE bundle = :textname AND entity_id = :entityid AND langcode = :langcode", [':textname' => $textname, ':entityid' => $entityid_dv, ':langcode' => $langcode])->fetchField();

//                   $other_fields['content'] = $field_content;
//                   $text_info['nid'] = json_decode($available_texts[$i]->nid, TRUE);
//                   $text_info['title'] = $available_texts[$i]->title;

//                 }

//               }
//               else {
//                 // No field exists.
//                 $flag = FALSE;
//               }

//               if ($flag == TRUE) {
//                 $text_info[$field] = $other_fields;

//               }
//               else {
//                 $message = [
//                   'success' => 0,
//                   'message' => "Field does not exist",

//                 ];
//                 $statuscode = 404;
//                 $response[] = $message;
//                 $response[] = $statuscode;

//               }

//             }
//           }

//         }
//         if ($mool_shloka_flag == TRUE) {
//           // When no parameters are given.
//           $node = Node::load($available_texts[$i]->nid);
//           // Add a mool s.
//           $mool_shloka['content'] = $node->field_gita_25232_text->value;
//           if ($metadata == 1) {
//             $metadata_mool_sholka = collect_metadata($available_texts[$i]->nid, 'field_ramayanamtest_25234_text', 'dv');
//             $mool_shloka['meta_data'] = json_decode($metadata_mool_sholka, TRUE);

//           }
//           $text_info['nid'] = json_decode($available_texts[$i]->nid, TRUE);
//           $text_info['title'] = $available_texts[$i]->title;
//           $text_info['field_ramayanamtest_25234_text'] = $mool_shloka;

//         }
//         $contents[] = $text_info;

//       }
//       $response[] = $contents;
//       $response[] = 200;

//     }
//   }
//   else {
//     if (isset($position) && $position > 0) {
//       $flag = TRUE;
//       $mool_shloka_flag = TRUE;

//       // If only position parameter is given, display the mool shloka.
//       $mool_shloka = [];
//       $other_fields = [];

//       $contents['title'] = $position;

//   //     if ($langcode == 'en') {
//   //       $entityid_en = get_entityId($position, $textname, $langcode);
//   //       $contents['nid'] = json_decode($entityid_en, TRUE);
//   //       // Display  mool shloka for that position.
//   //       $entityid_mool = get_entityId($position, $textname, 'dv');
//   //       $node_mool = Node::load($entityid_mool);
//   //       $mool_shloka['content'] = $node_mool->field_ramayanamtest_25234_text->value;
//   //       if ($metadata == 1) {
//   //         $metadata_mool = collect_metadata($entityid_mool, 'field_ramayanamtest_25234_text', 'dv');
//   //         $mool_shloka['meta_data'] = json_decode($metadata_mool, TRUE);
//   //       }

//   //     }
//   //     else {
//   //       $entityid = get_entityId($position, $textname, $langcode);
//   //       $contents['nid'] = json_decode($entityid, TRUE);
//   //       $node = Node::load($entityid);
//   //       $mool_shloka['content'] = $node->field_ramayanamtest_25234_text->value;
//   //       if ($metadata == 1) {
//   //         $metadata_mool = collect_metadata($entityid, 'field_ramayanamtest_25234_text', $langcode);
//   //         $mool_shloka['meta_data'] = json_decode($metadata_mool, TRUE);

//   //       }

//   //     }

//   //     // IF other parameter are given e.g field and language.
//   //     foreach ($parameters as $key => $parameter) {
//   //       $parameter_info = explode('_', $key);
//   //       if ($parameter_info[0] == 'field') {
//   //         if (count($parameter_info) >= 3) {
//   //           $field = 'field_' . $parameter_info[1] . '_' . $parameter_info[2] . '_' . $parameter_info[3];
//   //           $field_name = 'field_' . $parameter_info[1] . '_' . $parameter_info[2] . '_' . $parameter_info[3] . '_value';

//   //           $table_name = 'node__field_' . $textname . '_' . $parameter_info[2] . '_' . $parameter_info[3];

//   //           if (doesBundleHaveField('node', $textname, $field) == TRUE) {
//   //             // Get the content for the field from table.
//   //             $table_lang = db_query("SELECT langcode FROM " . $table_name . " WHERE bundle = :textname", [':textname' => $textname])->fetchField();
//   //             if ($mool_shloka == 0) {
//   //               $mool_shloka_flag = FALSE;
//   //             }

//   //             if ($table_lang == 'en') {
//   //               $entityid_en = get_entityId($position, $textname, 'en');

//   //               $field_content = db_query("SELECT $field_name FROM " . $table_name . " WHERE bundle = :textname AND entity_id = :entityid AND langcode = :langcode", [':textname' => $textname, ':entityid' => $entityid_en, ':langcode' => 'en'])->fetchField();

//   //               $other_fields['content'] = $field_content;
//   //               if ($metadata == 1) {
//   //                 $metadata_info = collect_metadata($entityid_en, $field, 'en');
//   //                 $other_fields['metadata'] = json_decode($metadata_info, TRUE);

//   //               }

//   //              // $contents[$field] = $other_fields;
//   //               $contents['entity_id'] = $entityid_en;

//   //             }

//   //             else {
//   //               $entityid_dv = get_entityId($position, $textname, $langcode);
//   //               $field_content = db_query("SELECT $field_name FROM " . $table_name . " WHERE bundle = :textname AND entity_id = :entityid AND langcode = :langcode", [':textname' => $textname, ':entityid' => $entityid_dv, ':langcode' => $langcode])->fetchField();

//   //               $other_fields['content'] = $field_content;
//   //               if ($metadata == 1) {
//   //                 $metadata_info = collect_metadata($entityid_dv, $field, $langcode);
//   //                 $other_fields['metadata'] = json_decode($metadata_info, TRUE);

//   //               }
//   //               $contents[$field] = $other_fields;

//   //             }

//   //           }
//   //           else {
//   //             $flag = FALSE;
//   //           }

//   //         }

//   //       }

//   //     }
//   //     if ($mool_shloka_flag == TRUE) {
//   //       $contents['field_ramayanamtest_25234_text'] = $mool_shloka;

//   //     }

//   //     if ($flag == FALSE) {
//   //       $message = [
//   //         'success' => 0,
//   //         'message' => "Field does not exist",

//   //       ];
//   //       $statuscode = 404;
//   //       $response[] = $message;
//   //       $response[] = $statuscode;

//   //     }
//   //     else {
//   //       $response[] = $contents;
//   //       $response[] = 200;
//   //     }

//      }
//    }

//   return $contents;

// }
